
server:
        build: ./server
        # ports: 
        # - "40510:8000"
        command: "node server.js"
client:
        build: ./client
        #ports: 
         # - "12345:8080"
        command: "node client.js"



                
